- .ci/init.sh
- .gitignore
- .travis.yml
- build.xml.template
- docs/howto.md
- scripts/generate-ant-file.sh
> Add Travis Support

- .ci/init.sh
- .travis.yml
- docs/index.html
> travis: Simplify CI process

- examples/hello-processing.R
- src/rprocessing/RLangPApplet.java
- src/rprocessing/applet/BuiltinApplet.java
> Add 2D built-in functions 

- src/rprocessing/IOUtil.java
- src/rprocessing/RLangPApplet.java
- src/rprocessing/Runner.java
- src/rprocessing/exception/NotFoundException.java
- src/rprocessing/exception/REvalException.java
- src/rprocessing/exception/RMIRuntimeException.java
- src/rprocessing/lancher/StandaloneSketch.java
- src/rprocessing/mode/RLangEditor.java
- src/rprocessing/mode/RLangInputHandler.java
- src/rprocessing/mode/RLangMode.java
- src/rprocessing/mode/RLangToolbar.java
- src/rprocessing/mode/run/ModeWaiter.java
- src/rprocessing/mode/run/OSXAdapter.java
- src/rprocessing/mode/run/PdeSketch.java
- src/rprocessing/mode/run/RMIUtils.java
- src/rprocessing/mode/run/SketchRunner.java
- src/rprocessing/mode/run/SketchServiceManager.java
- src/rprocessing/mode/run/SketchServiceRunner.java
https://www.codacy.com/app/gaocegege/Processing-R/dashboard?bid=4532171
> WIP: Fix coding style according to codacy

- examples/hello-processing.R
- examples/test-setup.R
- src/rprocessing/applet/BuiltinApplet.java
> builtin: Add curves function

- .gitignore
- build.xml.template
- src/test/IOUtilTest.java
> Fix ant report

- examples/object-oriented.R
> Add an object oriented example

- examples/trigonometry.R
- src/rprocessing/applet/BuiltinApplet.java
ref https://processing.org/tutorials/trig/
> examples: Add a new example about Trigonometry

- .ci/init.cmd
- .ci/init.sh
- .docker/generate-ant-file-in-docker.sh
- build.xml.template
- raw-docs/howto.md
- scripts/generate-ant-file.sh
- scripts/utils/generator-util.sh
> Optimize the script to generate build.xml

- .docker/generate-ant-file-in-docker.sh
- Dockerfile
> Docker: Update the docker config

- resources/keywords.txt
- src/rprocessing/mode/RLangEditor.java
- src/rprocessing/mode/RLangKeywordMap.java
- src/rprocessing/mode/RLangMode.java
- src/rprocessing/mode/RLangTokenMarker.java
- src/rprocessing/mode/SyntaxUtilities.java
> Fix comments highlight

- .appveyor.yml
- .travis.yml
> ci: Add ant package

- .ci/init.cmd
- .ci/init.sh
- .docker/generate-ant-file-in-docker.sh
- build.xml.template
- raw-docs/howto.md
- scripts/generate-ant-file.sh
- scripts/utils/generator-util.sh
- src/rprocessing/RLangPApplet.java
- src/rprocessing/Runner.java
- src/rprocessing/mode/RLangEditor.java
- src/rprocessing/mode/RLangMode.java
WIP
The problem is caused by thread communication. The PApplet does't block until the sketch stops.
ref #6 
> Make PApplet to be a singleton.

- LICENSE
> LICENSE: GPLv3

- .coafile
- .gitignore
- java-style.xml
- src/rprocessing/IOUtil.java
- src/rprocessing/RLangPApplet.java
- src/rprocessing/RunnableSketch.java
- src/rprocessing/Runner.java
- src/rprocessing/TreeCopier.java
- src/rprocessing/lancher/StandaloneSketch.java
- src/rprocessing/mode/RLangEditor.java
- src/rprocessing/mode/RLangInputHandler.java
- src/rprocessing/mode/RLangMode.java
- src/rprocessing/mode/RLangTokenMarker.java
- src/rprocessing/mode/run/ModeService.java
- src/rprocessing/mode/run/RMIUtils.java
- src/rprocessing/mode/run/SketchRunner.java
- src/rprocessing/mode/run/SketchServiceManager.java
- src/rprocessing/mode/run/SketchServiceRunner.java
- src/rprocessing/util/RScriptReader.java
- src/test/IOUtilTest.java
> Fix the code style according to coala

- src/rprocessing/Runner.java
> Runner: Exit when finished

- examples/reference/arc/arc2/arc2.rpde
- examples/reference/arc/arc3/arc3.rpde
- examples/reference/arc/arc4/arc4.rpde
- examples/reference/point/point2/point2.rpde
> reference: Fix the integer transfer

- examples/reference/arc/.property.yml
- examples/reference/box/.property.yml
- examples/reference/ellipse/.property.yml
- examples/reference/line/.property.yml
- examples/reference/point/.property.yml
- examples/reference/quad/.property.yml
- examples/reference/rect/.property.yml
> reference: Add description and parameters

- readme.md
> README: Add reference

- .ci/init.sh
- .travis.yml
- build.xml.template
> travis: Fix CI failure

- src/rprocessing/RLangPApplet.java
- src/rprocessing/RunnableSketch.java
- src/rprocessing/Runner.java
- src/rprocessing/applet/BuiltinApplet.java
- src/rprocessing/lancher/StandaloneSketch.java
- src/rprocessing/mode/RLangEditor.java
- src/rprocessing/mode/library/LibraryImporter.java
- src/rprocessing/mode/run/PdeSketch.java
```R
P3D <- "processing.opengl.PGraphics3D"
settings <- function() {
size(200, 200, P3D)
}
setup <- function() {
cam = PeasyCam$new(processing, 100)
cam$setMinimumDistance(50)
cam$setMaximumDistance(500)
}
draw <- function() {
rotateX(-.5)
rotateY(-.5)
background(0)
fill(255, 0, 0)
box(30)
pushMatrix()
translate(0, 0, 20)
fill(0, 0, 255)
box(5)
popMatrix()
}
```
The code works but now it is an ad-hoc implementation: https://github.com/gaocegege/Processing.R/pull/133/files#diff-914114bed9183352c9f4543df165fccbR48
> Support Processing libraries

- readme.md
ref #63 
You could use docker for 2D sketches but this approach is not maintained any more.
> badge: Deprecate docker

- examples/R Packages/Basics/Basics.rpde
- src/rprocessing/mode/RLangMode.java
> RLangMode: Add examples of R packages

- examples/Libraries/LibraryBasics/LibraryBasics.rpde
- examples/R Packages/Basics/Basics.rpde
- examples/R Packages/RPackageBasics/RPackageBasics.rpde
> examples: Rename examples of library and package

- build.xml.template
> build.xml: Add macOS specific check

- src/rprocessing/applet/BuiltinApplet.java
> BuiltinApplet: Add warnings for casting

- .coafile
- src/rprocessing/mode/RLangInputHandler.java
> RLangInputHandler: Replacing python with java

- examples/reference/focused/focused0/focused0.rpde
> focused: Add example

- src/rprocessing/RLangPApplet.java
- src/rprocessing/r/core.R
> Add built-in variables pixelWidth and pixelHeight

- examples/Basics/ThreeDimensionalCube/ThreeDimensionalCube.rpde
> ThreeDimensionalCube: Fix frameCount

- readme.md
The feature is supported in https://github.com/gaocegege/Processing.R/pull/171
> README: Remove limitations

- src/rprocessing/r/core.R
> core.R: Add print

- examples/Basics/StaticSketch/StaticSketch.rpde
- src/rprocessing/applet/BuiltinApplet.java
> example: Add more cases

- .ci/init.cmd
- .ci/init.sh
- .docker/generate-ant-file-in-docker.sh
- build.xml.template
- resources/mode.properties
- scripts/generate-ant-file.sh
- scripts/utils/generator-util.sh
- src/rprocessing/build.properties
> *: Add version in PDE

- .gitignore
- src/rprocessing/build.properties
> ignore: Ignore build.properties

- examples/Demo/FiguresTransformation/FiguresTransformation.rpde
- src/rprocessing/mode/RLangMode.java
> demo: Fix the demo

- build.xml.template
- docs/RLangMode.txt
- resources/RLangMode.txt
- resources/mode.properties
- scripts/deploy.sh
> *: Update the version

- examples/reference/day/day1/day1.rpde
- examples/reference/hour/hour1/hour1.rpde
- examples/reference/millis/millis1/millis1.rpde
- examples/reference/minute/minute1/minute1.rpde
- examples/reference/month/month1/month1.rpde
- examples/reference/second/second1/second1.rpde
- examples/reference/year/year1/year1.rpde
> reference: Add time

- src/rprocessing/RLangPApplet.java
- src/rprocessing/mode/run/SketchRunner.java
> SketchRunner: Redirect all errors to PDE console

- src/rprocessing/applet/BuiltinApplet.java
> BuiltinApplet: Add pixelDensity

- readme.md
> README: Fix links

- examples/reference/HALF_PI/HALF_PI1/.test.yml
- examples/reference/HALF_PI/HALF_PI1/HALF_PI1.rpde
- examples/reference/PI/PI1/.test.yml
- examples/reference/PI/PI1/PI1.rpde
- examples/reference/QUARTER_PI/QUARTER_PI1/.test.yml
- examples/reference/QUARTER_PI/QUARTER_PI1/QUARTER_PI1.rpde
- examples/reference/TAU/TAU1/.test.yml
- examples/reference/TAU/TAU1/TAU1.rpde
- examples/reference/TWO_PI/TWO_PI1/.test.yml
- examples/reference/TWO_PI/TWO_PI1/TWO_PI1.rpde
> reference: Add constants

- .ci/check-and-test.sh
- .ci/init-linux.sh
- .ci/init-macos.sh
- .travis.yml
Close #82 
https://travis-ci.org/gaocegege/Processing.R/jobs/255105401
We meet travis's bug, maybe.
> Add CI for macOS

- src/rprocessing/mode/RLangEditor.java
- src/rprocessing/util/Constant.java
> RLangEditor: Add reference open menu

- .docker/run-examples.sh
- scripts/deploy.sh
- scripts/utils/generator-util.sh
> scripts: Remove timezone settings

- .travis.yml
> .travis: Add allow_failures

- examples/reference/resetMatrix/resetMatrix1/resetMatrix1.rpde
Close https://github.com/gaocegege/Processing.R/issues/110
> resetMatrix: Add an example

- examples/reference/rectMode/.property.yml
> rectMode: Typo fix

- src/rprocessing/mode/run/SketchRunner.java
- src/rprocessing/r/core.R
- src/rprocessing/util/Printer.java
- src/rprocessing/util/StreamPrinter.java
> *: Support println

- src/rprocessing/mode/RLangEditor.java
> RLangEditor: Add about and tutorials

- src/rprocessing/r/core.R
Close #241 
I am going to support more user cases about statistical computing, PVector is the basis.
> core.R: Add support for PVector

- examples/Libraries/grafica/LifeExpectancy/LifeExpectancy.rpde
- src/rprocessing/r/core.R
> *: Add table and advanced exmaple for grafica
