.appveyor.yml
.ci/init.cmd
readme.md

WIP: appveyor: Add Windows CI

---

examples/hello-processing.R
src/rprocessing/applet/BuiltinApplet.java

Support built-in color functions

---

examples/3d-cube.R
src/rprocessing/RLangPApplet.java
src/rprocessing/applet/BuiltinApplet.java

examples: Add a 3d example

---

.coafile
.travis.yml
examples/Basics/BasicOperations/BasicOperations.rpde
examples/Basics/Draw/Draw.rpde
examples/Basics/ObjectOrientedProgramming/ObjectOrientedProgramming.rpde
examples/Basics/Settings/Settings.rpde
examples/Basics/Setup/Setup.rpde
examples/Basics/ThreeDimensionalCube/ThreeDimensionalCube.rpde
examples/Basics/Trigonometry/trigonometry.rpde

Closes #52 
Ref https://github.com/coala/coala-bears/issues/1750

coala: Add coala support

---

examples/reference/arc/.property.yml
examples/reference/box/.property.yml
examples/reference/ellipse/.property.yml
examples/reference/line/.property.yml
examples/reference/point/.property.yml
examples/reference/quad/.property.yml
examples/reference/rect/.property.yml

To set category and subcategory for reference docs, the information about it is needed in example/reference folders.

reference: Add category properties

---

src/rprocessing/RLangPApplet.java

😈   I add new keywords `mouseX` and `mouseY`. You can test by the following R code
```R
draw <- function() {
background(as.integer(204))
line(mouseX, mouseY, 80, mouseY);
}
```

feat: add mouseX and mouseY

---

src/rprocessing/RLangPApplet.java
src/rprocessing/applet/BuiltinApplet.java

Remove the function to BuiltinApplet

feat: move the function about mouse to BuiltinApplet

---

src/rprocessing/applet/BuiltinApplet.java

remove useless import in the BuiltinApplet.
I never use the apache ant in the IntelliJ IDEA. it takes me many time to setting the IDE to do the best. Should we have documents to tell the new contributors how to set the IDE ?

style: remove useless import

---

raw-docs/architecture.md

Add architecture documentation

---

src/rprocessing/r/core.R

core.R: Support static functions in PApplet

---

src/rprocessing/Runner.java
src/rprocessing/mode/library/LibraryImporter.java
src/rprocessing/r/import_library.R

```R
P3D <- "processing.opengl.PGraphics3D"
settings <- function() {
importLibrary("peasycam")
size(200, 200, P3D)
}
setup <- function() {
cam = PeasyCam$new(processing, 100)
cam$setMinimumDistance(50)
cam$setMaximumDistance(500)
}
draw <- function() {
rotateX(-.5)
rotateY(-.5)
background(0)
fill(255, 0, 0)
box(30)
pushMatrix()
translate(0, 0, 20)
fill(0, 0, 255)
box(5)
popMatrix()
}
```
Now we support to import library in settings, and I am not sure when we chould import libraries at the beginning of the code, since it is about real pre-processor, and it is in low priority since it is just syntax sugar.

LibraryImporter: Fix ad-hoc code

---

.ci/init.cmd
scripts/utils/generator-util.sh

The config about renjin is deprecated, just remove it from appveyor.

ci: Remove renjin specific config

---

src/rprocessing/RLangPApplet.java
src/rprocessing/Runner.java
src/rprocessing/exception/RSketchError.java
src/rprocessing/mode/run/SketchRunner.java

Close #24
We should redirect the exception into PDE.

Pop error or exception to PDE

---

readme.md

The coverage report has bugs caused by codacy, so remove the badge.
ref #103 and https://github.com/codacy/codacy-coverage-reporter/issues/56

badge: Remove codacy coverage badge

---

examples/Libraries/Basics/Basics.rpde
examples/reference/importLibrary/.property.yml
examples/reference/importLibrary/importLibrary0/importLibrary0.rpde
src/rprocessing/mode/RLangMode.java

Add reference and library example

---

src/rprocessing/RLangPApplet.java
src/rprocessing/applet/BuiltinApplet.java

Hi ~ 
I add keyboard event, you can test it by the following code.
```R
settings <- function() {
size(500, 500)
}
draw <- function() {
stdout$print(key)
#stdout$print(keyCode)
stdout$print("\n")
}
```

feat: add keyboard event

---

build.xml.template

build.xml: Add OS specific code

---

examples/Basics/BasicOperations/BasicOperations.rpde
examples/Basics/ThreeDimensionalCube/ThreeDimensionalCube.rpde
src/rprocessing/applet/BuiltinApplet.java

*: Add cast from double to int

---

src/rprocessing/RLangPApplet.java

RLangPApplet: Support static mode

---

src/rprocessing/applet/BuiltinApplet.java
src/rprocessing/r/core.R

core.R: Add colorMode specific constants

---

resources/RLangMode.txt
scripts/deploy.sh

*: Add deploy script

---

examples/Libraries/He_Mesh/Noise/Noise.rpde
examples/Libraries/He_Mesh/demo.rpde

hemesh: Add a new example
